### ISSUE TITLE
[P1] Example 1. MNIST CNN Prover & Verifier

### ISSUE THREAD

**Issue by chris-chris** [chris-chris/mina-zkml#13]

**Comment by energyGiver** [comment]
# LeNet-5 zkSNARK Proof Generation and Verification Plan

## Objectives
Add an example for proof generation and verification for MNIST CNN (LeNet-5) inference.

1. Extend the existing ONNX parser for LeNet-5 architecture
2. Implement proof generation & verification for LeNet-5 model
3. Write example code to test the entire process

# Implementation Steps

### 1. LeNet-5 Conversion (4 hours)
- Verify newly added operations(Max Pooling and 2d Convolution ) in the LeNet-5 ONNX model
- Convert LeNet-5 ONNX model to Struct Model 

### 2. Proof Generation and Verification for LeNet-5 (10 hours)
- Create LeNet-5 circuit using ProofSystem
- Generate inference proof, check verification results, and test fault cases

### 3. Write Example Code (6 hours)
- Implement a preprocess logic to prepare input data
- Confirm that zk inference result matches ground truth for inputs

# Estimated Time:
- LeNet-5 Conversion: 4 hours
- Proof Generation and Verification for LeNet-5: 10 hours
- Write Example Code: 6 hours

### Total: 20 hours
