### ISSUE TITLE
[P1] Implement more basic Operators for CNN

### ISSUE THREAD

**Issue by chris-chris** [chris-chris/mina-zkml#9]
# Goal
Implement matmul & flatten 

# Reference Code

# Description
implement matmul & flatten operator

- matmul
- flatten
- relu
- sigmoid

# Task Process
Open PR for the issue and create branch.
Write down technical specification to accomplish the task.
Comment down your estimated hours to complete the task.
I'll comment the estimated hours as well
Start the task
Track your time consumption while working
Comment out your actual time consumed to complete the task

**Comment by chris-chris** [comment]
@energyGiver Please write down the tech spec for a simple CNN zkml

**Comment by energyGiver** [comment]
# Objectives

Add operators to enable inference for the LeNet-5 ONNX model.

1. Implement the following operators:
    - **Convolution**: Perform element-wise multiplication.
    - **Average Pooling**: Calculate averages using a kernel-based approach.
2. Write unit tests to ensure the operators work correctly.

# Implementation Steps

## 1. Follow-up on the current progress

- **Tasks**:
    - Review updates made in the main branch.
    - Identify additional operations needed for LeNet-5 model zk inference.
- **Estimated Time**: 4 hours

## 2. Implement the operators

- **Tasks**:
    - Implement the following operations:
        - Convolution, Pooling, Softmax, Exponentiation
- **Estimated Time**: 8 hours

## 3. Write unit tests for all operators

- **Tasks**:
    - Create unit tests to verify the functionality of each operator.
- **Estimated Time**: 4 hours

# Estimated Time:

- Follow-up on current progress: 4 hours
- Implement the operators: 8 hours
- Write unit tests: 4 hours

### Total: 16 hours

**Comment by energyGiver** [comment]
# Objectives

Add operators to enable inference for the LeNet-5 ONNX model.

1. Implement the following operators:
    - **Convolution**: Perform element-wise multiplication.
    - **Average Pooling**: Calculate averages using a kernel-based approach.
2. Write unit tests to ensure the operators work correctly.

# Implementation Steps

## 1. Follow-up on the current progress

- **Tasks**:
    - Review updates made in the main branch.
    - Identify additional operations needed for LeNet-5 model zk inference.
- **Estimated Time**: 4 hours

## 2. Implement the operators

- **Tasks**:
    - Implement the following operations:
        - Convolution, Pooling, Softmax, Exponentiation
- **Estimated Time**: 8 hours

## 3. Write unit tests for all operators

- **Tasks**:
    - Create unit tests to verify the functionality of each operator.
- **Estimated Time**: 4 hours

# Estimated Time:

- Follow-up on current progress: 4 hours
- Implement the operators: 8 hours
- Write unit tests: 4 hours

### Total: 16 hours
